// clang-format off
#pragma once

#include "util.hpp"
#include "x86/memory_view.hpp"
#include "x86/thread_state.hpp"

namespace game {

GAME_UNIMPLEMENTED_STUB(ShowCursor);
GAME_UNIMPLEMENTED_STUB(GetCursorPos);
GAME_UNIMPLEMENTED_STUB(wvsprintfA);
GAME_UNIMPLEMENTED_STUB(MessageBoxA);
GAME_UNIMPLEMENTED_STUB(GetSystemMetrics);
GAME_UNIMPLEMENTED_STUB(DefWindowProcA);
GAME_UNIMPLEMENTED_STUB(ReleaseCapture);
GAME_UNIMPLEMENTED_STUB(GetMessageA);
GAME_UNIMPLEMENTED_STUB(DispatchMessageA);
GAME_UNIMPLEMENTED_STUB(PeekMessageA);
GAME_UNIMPLEMENTED_STUB(TranslateMessage);
GAME_UNIMPLEMENTED_STUB(LoadIconA);
GAME_UNIMPLEMENTED_STUB(LoadCursorA);
GAME_UNIMPLEMENTED_STUB(RegisterClassExA);
GAME_UNIMPLEMENTED_STUB(AdjustWindowRect);
GAME_UNIMPLEMENTED_STUB(GetDesktopWindow);
GAME_UNIMPLEMENTED_STUB(CreateWindowExA);
GAME_UNIMPLEMENTED_STUB(UpdateWindow);
GAME_UNIMPLEMENTED_STUB(SetCursor);
GAME_UNIMPLEMENTED_STUB(SetFocus);
GAME_UNIMPLEMENTED_STUB(SetForegroundWindow);
GAME_UNIMPLEMENTED_STUB(ShowWindow);
GAME_UNIMPLEMENTED_STUB(SetWindowLongA);
GAME_UNIMPLEMENTED_STUB(DestroyWindow);
GAME_UNIMPLEMENTED_STUB(BeginPaint);
GAME_UNIMPLEMENTED_STUB(EndPaint);
GAME_UNIMPLEMENTED_STUB(PostMessageA);
GAME_UNIMPLEMENTED_STUB(PostThreadMessageA);
GAME_UNIMPLEMENTED_STUB(PostQuitMessage);
GAME_UNIMPLEMENTED_STUB(SetCapture);
GAME_UNIMPLEMENTED_STUB(GetClientRect);
GAME_UNIMPLEMENTED_STUB(GetWindowRect);
GAME_UNIMPLEMENTED_STUB(SetRect);
GAME_UNIMPLEMENTED_STUB(UnregisterClassA);
GAME_UNIMPLEMENTED_STUB(SetActiveWindow);
GAME_UNIMPLEMENTED_STUB(GetForegroundWindow);
GAME_UNIMPLEMENTED_STUB(wsprintfA);
GAME_UNIMPLEMENTED_STUB(IsIconic);

} // namespace game
