#pragma once

#include "game/stubs/advapi32.hpp"
#include "game/stubs/d3d9.hpp"
#include "game/stubs/ddraw.hpp"
#include "game/stubs/dinput8.hpp"
#include "game/stubs/dsound.hpp"
#include "game/stubs/gdi32.hpp"
#include "game/stubs/kernel32.hpp"
#include "game/stubs/netapi32.hpp"
#include "game/stubs/shell32.hpp"
#include "game/stubs/shfolder.hpp"
#include "game/stubs/tapi32.hpp"
#include "game/stubs/user32.hpp"
#include "game/stubs/winmm.hpp"
#include "game/stubs/ws2_32.hpp"