// clang-format off
#pragma once

#include "util.hpp"
#include "x86/memory_view.hpp"
#include "x86/thread_state.hpp"

namespace app {

APP_UNIMPLEMENTED_STUB(ShowCursor);
APP_UNIMPLEMENTED_STUB(GetCursorPos);
APP_UNIMPLEMENTED_STUB(wvsprintfA);
APP_UNIMPLEMENTED_STUB(MessageBoxA);
APP_UNIMPLEMENTED_STUB(GetSystemMetrics);
APP_UNIMPLEMENTED_STUB(DefWindowProcA);
APP_UNIMPLEMENTED_STUB(ReleaseCapture);
APP_UNIMPLEMENTED_STUB(GetMessageA);
APP_UNIMPLEMENTED_STUB(DispatchMessageA);
APP_UNIMPLEMENTED_STUB(PeekMessageA);
APP_UNIMPLEMENTED_STUB(TranslateMessage);
APP_UNIMPLEMENTED_STUB(LoadIconA);
APP_UNIMPLEMENTED_STUB(LoadCursorA);
APP_UNIMPLEMENTED_STUB(RegisterClassExA);
APP_UNIMPLEMENTED_STUB(AdjustWindowRect);
APP_UNIMPLEMENTED_STUB(GetDesktopWindow);
APP_UNIMPLEMENTED_STUB(CreateWindowExA);
APP_UNIMPLEMENTED_STUB(UpdateWindow);
APP_UNIMPLEMENTED_STUB(SetCursor);
APP_UNIMPLEMENTED_STUB(SetFocus);
APP_UNIMPLEMENTED_STUB(SetForegroundWindow);
APP_UNIMPLEMENTED_STUB(ShowWindow);
APP_UNIMPLEMENTED_STUB(SetWindowLongA);
APP_UNIMPLEMENTED_STUB(DestroyWindow);
APP_UNIMPLEMENTED_STUB(BeginPaint);
APP_UNIMPLEMENTED_STUB(EndPaint);
APP_UNIMPLEMENTED_STUB(PostMessageA);
APP_UNIMPLEMENTED_STUB(PostThreadMessageA);
APP_UNIMPLEMENTED_STUB(PostQuitMessage);
APP_UNIMPLEMENTED_STUB(SetCapture);
APP_UNIMPLEMENTED_STUB(GetClientRect);
APP_UNIMPLEMENTED_STUB(GetWindowRect);
APP_UNIMPLEMENTED_STUB(SetRect);
APP_UNIMPLEMENTED_STUB(UnregisterClassA);
APP_UNIMPLEMENTED_STUB(SetActiveWindow);
APP_UNIMPLEMENTED_STUB(GetForegroundWindow);
APP_UNIMPLEMENTED_STUB(wsprintfA);
APP_UNIMPLEMENTED_STUB(IsIconic);

} // namespace app
